#!/bin/sh
#
# @name Canard Honghu Wing Fixed-Wing (Gazebo SITL)
#
# @type Plane with Canards
# @class Plane
#
# @output Motor1 throttle
# @output Servo1 left aileron
# @output Servo2 right aileron
# @output Servo3 left elevator
# @output Servo4 right elevator
# @output Servo5 left rudder
# @output Servo6 right rudder
# @output Servo7 left canard
# @output Servo8 right canard
#
# @maintainer <your-email>
#
# NOTE: This airframe matches the Gazebo model honghu_wing_150kg_v3 servo ordering:
#   Gazebo servo_0 = left_aileron  -> PX4 CS0
#   Gazebo servo_1 = right_aileron -> PX4 CS1
#   Gazebo servo_2 = left_elevator -> PX4 CS2
#   Gazebo servo_3 = right_elevator-> PX4 CS3
#   Gazebo servo_4 = left_rudder   -> PX4 CS4
#   Gazebo servo_5 = right_rudder  -> PX4 CS5
#   Gazebo servo_6 = left_canard   -> PX4 CS6
#   Gazebo servo_7 = right_canard  -> PX4 CS7

. ${R}etc/init.d/rc.fw_defaults

# ---------------------------------------------------------------------------
# Simulation environment core configuration
# ---------------------------------------------------------------------------
PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=honghu_wing_150kg_v3}

param set-default SIM_GZ_EN 1
param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_MAGSIM 1
param set-default SENS_EN_ARSPDSIM 1

# Airspeed and safety limits (tuned for simulation stability)
param set-default FW_AIRSPD_MAX 28
param set-default FW_AIRSPD_MIN 10
param set-default FW_AIRSPD_STALL 8
param set-default FW_AIRSPD_TRIM 16
param set-default MIS_TAKEOFF_ALT 35
param set-default NAV_LOITER_RAD 100
param set-default FW_LND_ANG 5
param set-default FW_LND_USETER 0
param set-default FW_LND_ABORT 0
param set-default RWTO_TKOFF 1
param set-default FW_W_EN 1

# ---------------------------------------------------------------------------
# Topology definition: 8 control surfaces matching Gazebo model
# ---------------------------------------------------------------------------
param set-default CA_AIRFRAME 1
param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX -0.75
param set-default CA_SV_CS_COUNT 8

# ---------------------------------------------------------------------------
# Control allocation mapping (matches Gazebo servo_0..servo_7 order)
# ---------------------------------------------------------------------------
# 0: Left Aileron -- roll control
param set-default CA_SV_CS0_TYPE  1
param set-default CA_SV_CS0_TRQ_R -0.5

# 1: Right Aileron -- roll control
param set-default CA_SV_CS1_TYPE  2
param set-default CA_SV_CS1_TRQ_R 0.5

# 2: Left Elevator -- pitch control
param set-default CA_SV_CS2_TYPE  3
param set-default CA_SV_CS2_TRQ_P 0.5

# 3: Right Elevator -- pitch control
param set-default CA_SV_CS3_TYPE  3
param set-default CA_SV_CS3_TRQ_P 0.5

# 4: Left Rudder -- yaw control
param set-default CA_SV_CS4_TYPE  4
param set-default CA_SV_CS4_TRQ_Y 1.0

# 5: Right Rudder -- yaw control
param set-default CA_SV_CS5_TYPE  4
param set-default CA_SV_CS5_TRQ_Y 1.0

# 6: Left Canard -- auxiliary pitch via canard state machine
param set-default CA_SV_CS6_TYPE  19
param set-default CA_SV_CS6_TRQ_P -0.5
param set-default CA_SV_CS6_CANARD 1.0

# 7: Right Canard -- auxiliary pitch via canard state machine
param set-default CA_SV_CS7_TYPE  20
param set-default CA_SV_CS7_TRQ_P -0.5
param set-default CA_SV_CS7_CANARD 1.0

# ---------------------------------------------------------------------------
# Gazebo simulation output bridge
# ---------------------------------------------------------------------------
param set-default SIM_GZ_EC_FUNC1 101 # Motor 1 throttle

param set-default SIM_GZ_SV_FUNC1 201 # Servo 1 -> CS0 (left aileron)
param set-default SIM_GZ_SV_FUNC2 202 # Servo 2 -> CS1 (right aileron)
param set-default SIM_GZ_SV_FUNC3 203 # Servo 3 -> CS2 (left elevator)
param set-default SIM_GZ_SV_FUNC4 204 # Servo 4 -> CS3 (right elevator)
param set-default SIM_GZ_SV_FUNC5 205 # Servo 5 -> CS4 (left rudder)
param set-default SIM_GZ_SV_FUNC6 206 # Servo 6 -> CS5 (right rudder)
param set-default SIM_GZ_SV_FUNC7 207 # Servo 7 -> CS6 (left canard)
param set-default SIM_GZ_SV_FUNC8 208 # Servo 8 -> CS7 (right canard)

param set-default SIM_GZ_EC_MIN1 10
param set-default SIM_GZ_EC_MAX1 4500
param set-default FD_ESCS_EN 0

# ---------------------------------------------------------------------------
# Canard state machine parameters
# ---------------------------------------------------------------------------
# FW_CANARD_TO:  Takeoff cruise canard setting (0=neutral, 1=max trailing-edge-down)
param set-default FW_CANARD_TO     0.5
# FW_CANARD_BRK: Aerodynamic braking canard setting (0=neutral, 1=max trailing-edge-up)
param set-default FW_CANARD_BRK    1.0
# FW_CANARD_LND_H:  Touchdown AGL height threshold [m]
param set-default FW_CANARD_LND_H  0.1
# FW_CANARD_LND_NZ: Touchdown normal load factor threshold [g]
param set-default FW_CANARD_LND_NZ 1.5
