#!/bin/sh
#
# @name Canard Honghu Wing Fixed-Wing
#
# @type Plane with Canards
# @class Plane
#
# @output Motor1 throttle
# @output Servo1 left aileron
# @output Servo2 right aileron
# @output Servo3 left elevator
# @output Servo4 right elevator
# @output Servo5 left rudder
# @output Servo6 right rudder
# @output Servo7 left canard
# @output Servo8 right canard
#
# @maintainer <your-email>
#

. ${R}etc/init.d/rc.fw_defaults

# ---------------------------------------------------------------------------
# Airframe geometry & control surface count
# ---------------------------------------------------------------------------
param set-default CA_AIRFRAME 1
param set-default CA_ROTOR_COUNT 1
param set-default CA_SV_CS_COUNT 8

# ---------------------------------------------------------------------------
# Control surface definitions
# ---------------------------------------------------------------------------

# 0: Left Aileron -- roll control
param set-default CA_SV_CS0_TYPE  1
param set-default CA_SV_CS0_TRQ_R -0.5

# 1: Right Aileron -- roll control
param set-default CA_SV_CS1_TYPE  2
param set-default CA_SV_CS1_TRQ_R 0.5

# 2: Left Elevator -- pitch control (conventional tail)
param set-default CA_SV_CS2_TYPE  3
param set-default CA_SV_CS2_TRQ_P 0.5

# 3: Right Elevator -- pitch control (conventional tail)
param set-default CA_SV_CS3_TYPE  3
param set-default CA_SV_CS3_TRQ_P 0.5

# 4: Left Rudder -- yaw control
param set-default CA_SV_CS4_TYPE  4
param set-default CA_SV_CS4_TRQ_Y 0.5

# 5: Right Rudder -- yaw control
param set-default CA_SV_CS5_TYPE  4
param set-default CA_SV_CS5_TRQ_Y 0.5

# 6: Left Canard -- auxiliary pitch via canard state machine
param set-default CA_SV_CS6_TYPE  19
param set-default CA_SV_CS6_TRQ_P -0.5
param set-default CA_SV_CS6_CANARD 1.0

# 7: Right Canard -- auxiliary pitch via canard state machine
param set-default CA_SV_CS7_TYPE  20
param set-default CA_SV_CS7_TRQ_P -0.5
param set-default CA_SV_CS7_CANARD 1.0

# ---------------------------------------------------------------------------
# PWM output mapping
# ---------------------------------------------------------------------------
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 201
param set-default PWM_MAIN_FUNC3 202
param set-default PWM_MAIN_FUNC4 203
param set-default PWM_MAIN_FUNC5 204
param set-default PWM_MAIN_FUNC6 205
param set-default PWM_MAIN_FUNC7 206
param set-default PWM_MAIN_FUNC8 207
param set-default PWM_MAIN_FUNC9 208

# ---------------------------------------------------------------------------
# PWM timer configuration (50 Hz for servos)
# ---------------------------------------------------------------------------
param set-default PWM_MAIN_TIM0 50
param set-default PWM_MAIN_TIM1 50
param set-default PWM_MAIN_TIM2 50

# ---------------------------------------------------------------------------
# Disarmed PWM values (us)
# ---------------------------------------------------------------------------
param set-default PWM_MAIN_DIS0 1000
param set-default PWM_MAIN_DIS1 1500
param set-default PWM_MAIN_DIS2 1500
param set-default PWM_MAIN_DIS3 1500
param set-default PWM_MAIN_DIS4 1500
param set-default PWM_MAIN_DIS5 1500
param set-default PWM_MAIN_DIS6 1500
param set-default PWM_MAIN_DIS7 1500
param set-default PWM_MAIN_DIS8 1500

# ---------------------------------------------------------------------------
# Canard state machine parameters
# ---------------------------------------------------------------------------
param set-default FW_CANARD_TO     0.5  # Takeoff/cruise: trailing edge down (0=neutral, 1=max)
param set-default FW_CANARD_BRK    1.0  # Aerodynamic braking: trailing edge up (0=neutral, 1=max)
param set-default FW_CANARD_LND_H  0.1  # Touchdown AGL height threshold [m]
param set-default FW_CANARD_LND_NZ 1.5  # Touchdown normal load factor threshold [g]
