%% 鸿鹄翼 V8 100 kg 平飞纵向控制链诊断
% 本文件是顺序执行脚本，不包含自定义函数。
% 目标：
%   1. 区分TECS/姿态外环的低频活动和俯仰率内环的高频活动；
%   2. 比较PX4升降舵目标角与Gazebo实际关节角；
%   3. 按当前PX4代码重构P/I/D/FF各项，不根据翔仪报告拟合参数。

%% 1. 输入和输出
if ispc
    flyHome = "\\wsl.localhost\Ubuntu-22.04\home\fly";
else
    flyHome = "/home/fly";
end

repoRoot = fullfile(flyHome, "PX4-Autopilot-NewAero");
comparisonFile = fullfile(repoRoot, "analysis_outputs", ...
    "honghu_v8_xiangyi_closed_loop_matlab", ...
    "closed_loop_comparison_results.mat");
ulogFiles = [ ...
    fullfile(repoRoot, "build", "px4_sitl_default", "rootfs", "log", ...
        "2026-07-28", "16_23_58.ulg"); ...
    fullfile(repoRoot, "build", "px4_sitl_default", "rootfs", "log", ...
        "2026-07-28", "16_35_51.ulg")];
outputDir = fullfile(repoRoot, "analysis_outputs", ...
    "honghu_v8_longitudinal_control_diagnosis");

assert(isfile(comparisonFile), "缺少闭环对比MAT文件。");
assert(all(isfile(ulogFiles)), "缺少100 kg重复飞行ULog。");
if ~isfolder(outputDir)
    mkdir(outputDir);
end

load(comparisonFile, "tracks", "routeCumulative");

%% 2. 当前控制参数
pitchRateP = 0.40;
pitchRateI = 0.04;
pitchRateD = 0.10;
pitchRateFF = 0.75;
pitchTrim = 0.03;
trimAirspeedMps = 45.0;
stallAirspeedMps = 24.5;
sampleTimeS = 0.05;
flatSegmentNumber = 5;

metricRecords = struct([]);
termRecords = struct([]);

%% 3. 分别分析两次PX4完整任务
for repeatNumber = 1:2
    oneTrack = tracks{repeatNumber + 2};
    innerStart = routeCumulative(flatSegmentNumber) + 300;
    innerEnd = routeCumulative(flatSegmentNumber + 1) - 300;
    flatMask = ...
        oneTrack.RouteSegment == flatSegmentNumber & ...
        oneTrack.RouteProgressM >= innerStart & ...
        oneTrack.RouteProgressM <= innerEnd & ...
        oneTrack.HeightAGLM >= 50 & ...
        oneTrack.TASMps >= 40 & oneTrack.TASMps <= 48 & ...
        abs(oneTrack.RollDeg) <= 5 & ...
        abs(oneTrack.VerticalSpeedMps) <= 0.5 & ...
        abs(oneTrack.QDegS) <= 1;

    flatTime = oneTrack.TimeS(flatMask);
    assert(numel(flatTime) > 500, "共同平飞段样本不足。");
    uniformTime = (flatTime(1):sampleTimeS:flatTime(end))';

    ulogObject = ulogreader(ulogFiles(repeatNumber));
    wantedTopics = [ ...
        "vehicle_global_position", "vehicle_attitude_setpoint", ...
        "vehicle_rates_setpoint", "vehicle_angular_velocity", ...
        "rate_ctrl_status", "vehicle_torque_setpoint", ...
        "actuator_servos", "tecs_status"];
    topicRows = readTopicMsgs(ulogObject, "TopicNames", wantedTopics);
    topicNames = string(topicRows.TopicNames);

    globalRow = find(topicNames == "vehicle_global_position", 1);
    attitudeSetpointRow = find(topicNames == ...
        "vehicle_attitude_setpoint", 1);
    rateSetpointRow = find(topicNames == "vehicle_rates_setpoint", 1);
    angularVelocityRow = find(topicNames == ...
        "vehicle_angular_velocity", 1);
    rateStatusRow = find(topicNames == "rate_ctrl_status", 1);
    torqueRow = find(topicNames == "vehicle_torque_setpoint", 1);
    actuatorRow = find(topicNames == "actuator_servos", 1);
    tecsRow = find(topicNames == "tecs_status", 1);
    assert(all(~isempty([globalRow, attitudeSetpointRow, ...
        rateSetpointRow, angularVelocityRow, rateStatusRow, ...
        torqueRow, actuatorRow, tecsRow])), ...
        "ULog缺少纵向控制链主题。");

    globalMessages = topicRows.TopicMessages{globalRow};
    logTimeOrigin = seconds(globalMessages.timestamp(1));

    attitudeSetpointMessages = ...
        topicRows.TopicMessages{attitudeSetpointRow};
    attitudeSetpointTime = seconds( ...
        attitudeSetpointMessages.timestamp) - logTimeOrigin;
    [attitudeSetpointTime, uniqueIndex] = unique( ...
        attitudeSetpointTime, "stable");
    attitudeSetpointQuaternion = ...
        attitudeSetpointMessages.q_d(uniqueIndex, :);
    attitudePitchSetpointDeg = rad2deg(asin(max(-1, min(1, ...
        2 * (attitudeSetpointQuaternion(:, 1) .* ...
        attitudeSetpointQuaternion(:, 3) - ...
        attitudeSetpointQuaternion(:, 4) .* ...
        attitudeSetpointQuaternion(:, 2))))));
    attitudePitchSetpointDeg = interp1(attitudeSetpointTime, ...
        attitudePitchSetpointDeg, uniformTime, "linear", "extrap");

    rateSetpointMessages = topicRows.TopicMessages{rateSetpointRow};
    rateSetpointTime = seconds(rateSetpointMessages.timestamp) - ...
        logTimeOrigin;
    [rateSetpointTime, uniqueIndex] = unique( ...
        rateSetpointTime, "stable");
    pitchRateSetpointRadS = interp1(rateSetpointTime, ...
        rateSetpointMessages.pitch(uniqueIndex), uniformTime, ...
        "linear", "extrap");

    angularVelocityMessages = ...
        topicRows.TopicMessages{angularVelocityRow};
    angularVelocityTime = seconds( ...
        angularVelocityMessages.timestamp) - logTimeOrigin;
    [angularVelocityTime, uniqueIndex] = unique( ...
        angularVelocityTime, "stable");
    pitchRateRadS = interp1(angularVelocityTime, ...
        angularVelocityMessages.xyz(uniqueIndex, 2), uniformTime, ...
        "linear", "extrap");
    pitchAccelerationRadS2 = interp1(angularVelocityTime, ...
        angularVelocityMessages.xyz_derivative(uniqueIndex, 2), ...
        uniformTime, "linear", "extrap");

    rateStatusMessages = topicRows.TopicMessages{rateStatusRow};
    rateStatusTime = seconds(rateStatusMessages.timestamp) - ...
        logTimeOrigin;
    [rateStatusTime, uniqueIndex] = unique(rateStatusTime, "stable");
    pitchIntegrator = interp1(rateStatusTime, ...
        rateStatusMessages.pitchspeed_integ(uniqueIndex), ...
        uniformTime, "linear", "extrap");

    torqueMessages = topicRows.TopicMessages{torqueRow};
    torqueTime = seconds(torqueMessages.timestamp) - logTimeOrigin;
    [torqueTime, uniqueIndex] = unique(torqueTime, "stable");
    pitchTorqueSetpoint = interp1(torqueTime, ...
        torqueMessages.xyz(uniqueIndex, 2), uniformTime, ...
        "linear", "extrap");

    actuatorMessages = topicRows.TopicMessages{actuatorRow};
    actuatorTime = seconds(actuatorMessages.timestamp) - ...
        logTimeOrigin;
    [actuatorTime, uniqueIndex] = unique(actuatorTime, "stable");
    elevatorTargetNormalized = mean( ...
        actuatorMessages.control(uniqueIndex, 3:4), 2);
    elevatorTargetDeg = interp1(actuatorTime, ...
        30 * elevatorTargetNormalized, uniformTime, ...
        "linear", "extrap");

    tecsMessages = topicRows.TopicMessages{tecsRow};
    tecsTime = seconds(tecsMessages.timestamp) - logTimeOrigin;
    [tecsTime, uniqueIndex] = unique(tecsTime, "stable");
    tecsAltitudeSetpointM = interp1(tecsTime, ...
        tecsMessages.altitude_sp(uniqueIndex), uniformTime, ...
        "linear", "extrap");
    tecsAltitudeReferenceM = interp1(tecsTime, ...
        tecsMessages.altitude_reference(uniqueIndex), uniformTime, ...
        "linear", "extrap");
    tecsAirspeedSetpointMps = interp1(tecsTime, ...
        tecsMessages.true_airspeed_sp(uniqueIndex), uniformTime, ...
        "linear", "extrap");
    tecsAirspeedMps = interp1(tecsTime, ...
        tecsMessages.true_airspeed_filtered(uniqueIndex), uniformTime, ...
        "linear", "extrap");
    tecsPitchSetpointDeg = rad2deg(interp1(tecsTime, ...
        tecsMessages.pitch_sp_rad(uniqueIndex), uniformTime, ...
        "linear", "extrap"));
    tecsPitchIntegratorDeg = rad2deg(interp1(tecsTime, ...
        tecsMessages.pitch_integ(uniqueIndex), uniformTime, ...
        "linear", "extrap"));

    trackTime = oneTrack.TimeS;
    [trackTime, uniqueIndex] = unique(trackTime, "stable");
    pitchDeg = interp1(trackTime, oneTrack.PitchDeg(uniqueIndex), ...
        uniformTime, "linear", "extrap");
    heightM = interp1(trackTime, oneTrack.HeightAGLM(uniqueIndex), ...
        uniformTime, "linear", "extrap");
    trueAirspeedMps = interp1(trackTime, ...
        oneTrack.TASMps(uniqueIndex), uniformTime, ...
        "linear", "extrap");
    elevatorActualDeg = interp1(trackTime, ...
        oneTrack.DeltaEDeg(uniqueIndex), uniformTime, ...
        "linear", "extrap");

    %% 4. 按PX4代码重构俯仰率控制器各项
    airspeedConstrainedMps = max(trueAirspeedMps, ...
        stallAirspeedMps);
    airspeedScaling = trimAirspeedMps ./ airspeedConstrainedMps;
    pitchRateErrorRadS = pitchRateSetpointRadS - pitchRateRadS;
    pTerm = pitchRateP * pitchRateErrorRadS;
    iTerm = pitchIntegrator;
    dTerm = -pitchRateD * pitchAccelerationRadS2;
    ffTerm = pitchRateFF ./ airspeedScaling .* ...
        pitchRateSetpointRadS;
    reconstructedPitchTorque = ...
        (pTerm + iTerm + dTerm + ffTerm) .* airspeedScaling.^2 ...
        + pitchTrim * airspeedScaling.^2;

    %% 5. 统一频谱和波动指标
    signalNames = [ ...
        "PitchDeg", "PitchSetpointDeg", ...
        "PitchRateDegS", "PitchRateSetpointDegS", ...
        "PitchTorque", "PTerm", "ITerm", "DTerm", "FFTerm", ...
        "ElevatorTargetDeg", "ElevatorActualDeg", ...
        "HeightErrorM", "AirspeedErrorMps"];
    signalMatrix = [ ...
        pitchDeg, attitudePitchSetpointDeg, ...
        rad2deg(pitchRateRadS), rad2deg(pitchRateSetpointRadS), ...
        pitchTorqueSetpoint, pTerm, iTerm, dTerm, ffTerm, ...
        elevatorTargetDeg, elevatorActualDeg, ...
        tecsAltitudeSetpointM - tecsAltitudeReferenceM, ...
        tecsAirspeedSetpointMps - tecsAirspeedMps];

    for signalNumber = 1:numel(signalNames)
        detrendedSignal = detrend(signalMatrix(:, signalNumber), 1);
        sampleCount = numel(detrendedSignal);
        spectrum = abs(fft(detrendedSignal)) / sampleCount;
        frequencyHz = (0:sampleCount - 1)' / ...
            (sampleCount * sampleTimeS);
        validFrequency = frequencyHz >= 0.05 & frequencyHz <= 5.0;
        candidateSpectrum = spectrum;
        candidateSpectrum(~validFrequency) = -Inf;
        [~, peakIndex] = max(candidateSpectrum);

        oneMetric = struct;
        oneMetric.Repeat = repeatNumber;
        oneMetric.Signal = signalNames(signalNumber);
        oneMetric.Mean = mean(signalMatrix(:, signalNumber));
        oneMetric.StdDetrended = std(detrendedSignal);
        oneMetric.P90Range = prctile(detrendedSignal, 95) - ...
            prctile(detrendedSignal, 5);
        oneMetric.DominantHz = frequencyHz(peakIndex);
        if isempty(metricRecords)
            metricRecords = oneMetric;
        else
            metricRecords(end + 1) = orderfields( ...
                oneMetric, metricRecords); %#ok<SAGROW>
        end
    end

    %% 6. 控制项贡献和执行机构跟随
    highFrequencyWindowSamples = round(1.0 / sampleTimeS);
    torqueHigh = pitchTorqueSetpoint - movmean( ...
        pitchTorqueSetpoint, highFrequencyWindowSamples);
    pHigh = pTerm - movmean(pTerm, highFrequencyWindowSamples);
    dHigh = dTerm - movmean(dTerm, highFrequencyWindowSamples);
    ffHigh = ffTerm - movmean(ffTerm, highFrequencyWindowSamples);
    targetHigh = elevatorTargetDeg - movmean( ...
        elevatorTargetDeg, highFrequencyWindowSamples);
    actualHigh = elevatorActualDeg - movmean( ...
        elevatorActualDeg, highFrequencyWindowSamples);

    termRecord = struct;
    termRecord.Repeat = repeatNumber;
    termRecord.DurationS = uniformTime(end) - uniformTime(1);
    termRecord.TorqueReconstructionRMSE = sqrt(mean( ...
        (reconstructedPitchTorque - pitchTorqueSetpoint).^2));
    termRecord.ElevatorTargetActualRMSEDeg = sqrt(mean( ...
        (elevatorTargetDeg - elevatorActualDeg).^2));
    termRecord.ElevatorTargetActualHighCorr = corr( ...
        targetHigh, actualHigh);
    termRecord.TorquePHighCorr = corr(torqueHigh, pHigh);
    termRecord.TorqueDHighCorr = corr(torqueHigh, dHigh);
    termRecord.TorqueFFHighCorr = corr(torqueHigh, ffHigh);
    termRecord.PTermRMS = sqrt(mean(pTerm.^2));
    termRecord.ITermRMS = sqrt(mean(iTerm.^2));
    termRecord.DTermRMS = sqrt(mean(dTerm.^2));
    termRecord.FFTermRMS = sqrt(mean(ffTerm.^2));
    termRecord.PitchSetpointTECSRMSEDeg = sqrt(mean( ...
        (attitudePitchSetpointDeg - tecsPitchSetpointDeg).^2));
    if isempty(termRecords)
        termRecords = termRecord;
    else
        termRecords(end + 1) = orderfields( ...
            termRecord, termRecords); %#ok<SAGROW>
    end

    %% 7. 绘制控制链时域
    plotTime = uniformTime - uniformTime(1);
    figureControl = figure("Visible", "off", "Color", "white", ...
        "Position", [80, 80, 1400, 1100]);
    layoutControl = tiledlayout(figureControl, 3, 2, ...
        "TileSpacing", "compact", "Padding", "compact");

    axisPitch = nexttile(layoutControl);
    plot(axisPitch, plotTime, pitchDeg, "LineWidth", 1.0, ...
        "DisplayName", "pitch");
    hold(axisPitch, "on");
    plot(axisPitch, plotTime, attitudePitchSetpointDeg, ...
        "LineWidth", 1.0, "DisplayName", "pitch setpoint");
    hold(axisPitch, "off");
    grid(axisPitch, "on");
    ylabel(axisPitch, "deg");
    title(axisPitch, "俯仰姿态外环");
    legend(axisPitch, "Location", "best");

    axisRate = nexttile(layoutControl);
    plot(axisRate, plotTime, rad2deg(pitchRateRadS), ...
        "LineWidth", 1.0, "DisplayName", "q");
    hold(axisRate, "on");
    plot(axisRate, plotTime, rad2deg(pitchRateSetpointRadS), ...
        "LineWidth", 1.0, "DisplayName", "q setpoint");
    hold(axisRate, "off");
    grid(axisRate, "on");
    ylabel(axisRate, "deg/s");
    title(axisRate, "俯仰角速率内环");
    legend(axisRate, "Location", "best");

    axisTorque = nexttile(layoutControl);
    plot(axisTorque, plotTime, pitchTorqueSetpoint, ...
        "Color", [0, 0, 0], "LineWidth", 1.1, ...
        "DisplayName", "published torque");
    hold(axisTorque, "on");
    plot(axisTorque, plotTime, pTerm, "DisplayName", "P");
    plot(axisTorque, plotTime, iTerm, "DisplayName", "I");
    plot(axisTorque, plotTime, dTerm, "DisplayName", "D");
    plot(axisTorque, plotTime, ffTerm, "DisplayName", "FF");
    hold(axisTorque, "off");
    grid(axisTorque, "on");
    ylabel(axisTorque, "normalized");
    title(axisTorque, "俯仰率控制器分项");
    legend(axisTorque, "Location", "best", "NumColumns", 3);

    axisElevator = nexttile(layoutControl);
    plot(axisElevator, plotTime, elevatorTargetDeg, ...
        "LineWidth", 1.0, "DisplayName", "PX4 target");
    hold(axisElevator, "on");
    plot(axisElevator, plotTime, elevatorActualDeg, ...
        "LineWidth", 1.0, "DisplayName", "Gazebo actual");
    hold(axisElevator, "off");
    grid(axisElevator, "on");
    ylabel(axisElevator, "deg");
    title(axisElevator, "升降舵目标与实际");
    legend(axisElevator, "Location", "best");

    axisEnergy = nexttile(layoutControl);
    yyaxis(axisEnergy, "left");
    plot(axisEnergy, plotTime, ...
        tecsAltitudeSetpointM - tecsAltitudeReferenceM, ...
        "LineWidth", 1.0, "DisplayName", "altitude error");
    ylabel(axisEnergy, "高度误差 / m");
    yyaxis(axisEnergy, "right");
    plot(axisEnergy, plotTime, ...
        tecsAirspeedSetpointMps - tecsAirspeedMps, ...
        "LineWidth", 1.0, "DisplayName", "TAS error");
    ylabel(axisEnergy, "空速误差 / (m/s)");
    grid(axisEnergy, "on");
    title(axisEnergy, "TECS误差");

    axisIntegrator = nexttile(layoutControl);
    plot(axisIntegrator, plotTime, tecsPitchIntegratorDeg, ...
        "LineWidth", 1.0, "DisplayName", "TECS pitch I");
    hold(axisIntegrator, "on");
    plot(axisIntegrator, plotTime, rad2deg(pitchIntegrator), ...
        "LineWidth", 1.0, "DisplayName", "rate I equivalent");
    hold(axisIntegrator, "off");
    grid(axisIntegrator, "on");
    ylabel(axisIntegrator, "deg equivalent");
    title(axisIntegrator, "积分器状态");
    legend(axisIntegrator, "Location", "best");

    xlabel(layoutControl, "平飞航段内时间 / s");
    title(layoutControl, "V8 100 kg纵向控制链：repeat " + ...
        string(repeatNumber));
    exportgraphics(figureControl, fullfile(outputDir, ...
        "longitudinal_control_chain_repeat_" + ...
        string(repeatNumber) + ".png"), "Resolution", 220);
    close(figureControl);

    %% 8. 保存本架次统一时序
    diagnosticData = [ ...
        uniformTime(:), pitchDeg(:), attitudePitchSetpointDeg(:), ...
        tecsPitchSetpointDeg(:), rad2deg(pitchRateRadS(:)), ...
        rad2deg(pitchRateSetpointRadS(:)), pitchAccelerationRadS2(:), ...
        pitchTorqueSetpoint(:), reconstructedPitchTorque(:), ...
        pTerm(:), iTerm(:), dTerm(:), ffTerm(:), ...
        elevatorTargetDeg(:), elevatorActualDeg(:), ...
        heightM(:), trueAirspeedMps(:), ...
        (tecsAltitudeSetpointM(:) - tecsAltitudeReferenceM(:)), ...
        (tecsAirspeedSetpointMps(:) - tecsAirspeedMps(:)), ...
        tecsPitchIntegratorDeg(:)];
    diagnosticTimeseries = array2table(diagnosticData);
    diagnosticTimeseries.Properties.VariableNames = { ...
        'TimeS', 'PitchDeg', 'PitchSetpointDeg', ...
        'TECSPitchSetpointDeg', 'PitchRateDegS', ...
        'PitchRateSetpointDegS', 'PitchAccelerationRadS2', ...
        'PitchTorqueSetpoint', 'ReconstructedPitchTorque', ...
        'PTerm', 'ITerm', 'DTerm', 'FFTerm', ...
        'ElevatorTargetDeg', 'ElevatorActualDeg', ...
        'HeightM', 'TASMps', 'AltitudeErrorM', ...
        'AirspeedErrorMps', 'TECSPitchIntegratorDeg'};
    writetable(diagnosticTimeseries, fullfile(outputDir, ...
        "longitudinal_timeseries_repeat_" + ...
        string(repeatNumber) + ".csv"));
end

%% 9. 汇总
signalMetrics = struct2table(metricRecords);
controlTermMetrics = struct2table(termRecords);
writetable(signalMetrics, fullfile(outputDir, ...
    "longitudinal_signal_metrics.csv"));
writetable(controlTermMetrics, fullfile(outputDir, ...
    "longitudinal_control_term_metrics.csv"));

summary = struct;
summary.generatedBy = "MATLAB R2025a sequential script";
summary.flatSegment = flatSegmentNumber;
summary.parameters = struct( ...
    "FW_PR_P", pitchRateP, "FW_PR_I", pitchRateI, ...
    "FW_PR_D", pitchRateD, "FW_PR_FF", pitchRateFF, ...
    "TRIM_PITCH", pitchTrim, ...
    "FW_AIRSPD_TRIM", trimAirspeedMps);
summary.signalMetrics = table2struct(signalMetrics);
summary.controlTermMetrics = table2struct(controlTermMetrics);
summary.boundary = [ ...
    "Xiangyi report gains are not copied. This script diagnoses the " + ...
    "current PX4 control chain from logged setpoints, outputs and actual " + ...
    "Gazebo joint angles."];
writelines(jsonencode(summary, "PrettyPrint", true), ...
    fullfile(outputDir, "longitudinal_control_summary.json"));

disp("纵向控制链信号指标：")
disp(signalMetrics)
disp("纵向控制项与执行机构指标：")
disp(controlTermMetrics)
disp("纵向控制链诊断完成：")
disp(outputDir)
