%% 5. 按共同任务几何比较四架次闭环轨迹与稳定平飞段

planPayload = jsondecode(fileread(planFile));
missionItems = planPayload.mission.items;
routeLatitude = [];
routeLongitude = [];
routeAltitude = [];
for itemNumber = 1:numel(missionItems)
    if iscell(missionItems)
        oneItem = missionItems{itemNumber};
    else
        oneItem = missionItems(itemNumber);
    end
    if ~isfield(oneItem, "params")
        continue
    end
    oneParams = oneItem.params;
    if iscell(oneParams)
        oneParams = cell2mat(oneParams);
    end
    if numel(oneParams) >= 7 && isfinite(oneParams(5)) && ...
            isfinite(oneParams(6)) && abs(oneParams(5)) > 1 && ...
            abs(oneParams(6)) > 1
        routeLatitude(end+1, 1) = oneParams(5); %#ok<SAGROW>
        routeLongitude(end+1, 1) = oneParams(6); %#ok<SAGROW>
        routeAltitude(end+1, 1) = oneParams(7); %#ok<SAGROW>
    end
end
assert(numel(routeLatitude) >= 10, "任务航线有效地理点数量异常。");

referenceLatitude = routeLatitude(1);
referenceLongitude = routeLongitude(1);
metresPerDegreeLatitude = 111111.0;
metresPerDegreeLongitude = 111111.0 * cosd(referenceLatitude);
routeEast = (routeLongitude - referenceLongitude) * ...
    metresPerDegreeLongitude;
routeNorth = (routeLatitude - referenceLatitude) * ...
    metresPerDegreeLatitude;
routePoints = [routeEast, routeNorth];
routeVectors = diff(routePoints, 1, 1);
routeSegmentLengths = vecnorm(routeVectors, 2, 2);
routeCumulative = [0; cumsum(routeSegmentLengths)];

trackResults = struct([]);
trackMetrics = table;
segmentMetrics = table;
turnMetrics = table;
missionSwitchMetrics = table;
flatSegmentMetrics = table;
touchdownMetrics = table;

for caseIndex = 1:numel(flightCases)
    one = flightCases(caseIndex);
    eastM = (one.LongitudeDeg - referenceLongitude) * ...
        metresPerDegreeLongitude;
    northM = (one.LatitudeDeg - referenceLatitude) * ...
        metresPerDegreeLatitude;
    sampleCount = numel(one.TimeS);
    progressM = nan(sampleCount, 1);
    crossTrackM = nan(sampleCount, 1);
    segmentIndex = zeros(sampleCount, 1);
    alongSegmentM = nan(sampleCount, 1);
    activeSegment = 1;

    for sample = 1:sampleCount
        point = [eastM(sample), northM(sample)];
        bestDistance = inf;
        bestProgress = NaN;
        bestCrossTrack = NaN;
        bestSegment = 0;
        bestAlong = NaN;
        % 航线末端会回到起飞区域，不能逐样本在全航线中寻找最近
        % 线段，否则起飞样本可能被错误匹配到着陆段。投影搜索仅在
        % 当前线段及下一线段间前进，使累计航线进度保持有序。
        candidateSegments = activeSegment:min( ...
            activeSegment + 1, size(routeVectors, 1));
        for segment = candidateSegments
            vector = routeVectors(segment, :);
            vectorLengthSquared = dot(vector, vector);
            if vectorLengthSquared <= 0
                continue
            end
            relative = point - routePoints(segment, :);
            fraction = max(0, min(1, dot(relative, vector) / ...
                vectorLengthSquared));
            projection = routePoints(segment, :) + fraction * vector;
            difference = point - projection;
            distance = norm(difference);
            signedCrossTrack = ...
                (vector(1) * difference(2) - vector(2) * difference(1)) / ...
                sqrt(vectorLengthSquared);
            if distance < bestDistance
                bestDistance = distance;
                bestProgress = routeCumulative(segment) + ...
                    fraction * routeSegmentLengths(segment);
                bestCrossTrack = signedCrossTrack;
                bestSegment = segment;
                bestAlong = fraction * routeSegmentLengths(segment);
            end
        end
        progressM(sample) = bestProgress;
        crossTrackM(sample) = bestCrossTrack;
        segmentIndex(sample) = bestSegment;
        alongSegmentM(sample) = bestAlong;
        activeSegment = max(activeSegment, bestSegment);
    end

    % 只比较共同TAKEOFF任务点之后的空中航线。起飞点之前的跑道段
    % 会被折线投影钳在首点，若混入统计会把“发射点到起飞点”的
    % 几何距离误报为航迹横向误差。
    airborne = one.HeightAGLM >= 5 & one.TASMps >= 20 & ...
        progressM >= 1 & isfinite(progressM) & isfinite(crossTrackM);
    trackMetrics = [trackMetrics; table( ...
        one.Source, one.Name, nnz(airborne), ...
        sqrt(mean(crossTrackM(airborne).^2)), ...
        prctile(abs(crossTrackM(airborne)), 95), ...
        max(abs(crossTrackM(airborne))), ...
        min(one.HeightAGLM(airborne)), max(one.HeightAGLM(airborne)), ...
        min(one.TASMps(airborne)), max(one.TASMps(airborne)), ...
        max(abs(one.RollDeg(airborne))), ...
        max(abs(one.PitchDeg(airborne))), ...
        VariableNames=["Source", "Flight", "AirborneSamples", ...
        "CrossTrackRMSM", "CrossTrackP95M", "CrossTrackMaxM", ...
        "HeightMinM", "HeightMaxM", "TASMinMps", "TASMaxMps", ...
        "AbsRollMaxDeg", "AbsPitchMaxDeg"])]; %#ok<AGROW>

    for segment = 1:numel(routeSegmentLengths)
        segmentMask = airborne & segmentIndex == segment;
        if nnz(segmentMask) >= 10
            segmentMetrics = [segmentMetrics; table( ...
                one.Source, one.Name, segment, nnz(segmentMask), ...
                sqrt(mean(crossTrackM(segmentMask).^2)), ...
                prctile(abs(crossTrackM(segmentMask)), 95), ...
                max(abs(crossTrackM(segmentMask))), ...
                mean(one.HeightAGLM(segmentMask)), ...
                mean(one.TASMps(segmentMask)), ...
                max(abs(one.RollDeg(segmentMask))), ...
                max(abs(one.PitchDeg(segmentMask))), ...
                one.TimeS(find(segmentMask, 1, "last")) - ...
                    one.TimeS(find(segmentMask, 1, "first")), ...
                VariableNames=["Source", "Flight", "Segment", "Samples", ...
                "CrossTrackRMSM", "CrossTrackP95M", "CrossTrackMaxM", ...
                "HeightMeanM", "TASMeanMps", "AbsRollMaxDeg", ...
                "AbsPitchMaxDeg", "ObservedDurationS"])]; %#ok<AGROW>
        end

        flatMask = airborne & segmentIndex == segment & ...
            alongSegmentM >= 300 & ...
            alongSegmentM <= routeSegmentLengths(segment) - 300 & ...
            abs(one.RollDeg) <= 3 & ...
            abs(one.VerticalSpeedMps) <= 0.3 & ...
            one.TASMps >= 35 & one.TASMps <= 50;
        if nnz(flatMask) < 20
            continue
        end
        flatSegmentMetrics = [flatSegmentMetrics; table( ...
            one.Source, one.Name, segment, nnz(flatMask), ...
            mean(one.HeightAGLM(flatMask)), std(detrend( ...
            one.HeightAGLM(flatMask))), ...
            mean(one.TASMps(flatMask)), std(detrend(one.TASMps(flatMask))), ...
            mean(one.PitchDeg(flatMask)), std(detrend( ...
            one.PitchDeg(flatMask))), ...
            mean(one.RollDeg(flatMask)), ...
            mean(one.DeltaDocDeg(flatMask, 2)), ...
            std(detrend(one.DeltaDocDeg(flatMask, 2))), ...
            mean(one.DeltaDocDeg(flatMask, 4)), ...
            mean(one.ThrottleState(flatMask)), ...
            mean(caseResults(caseIndex).ThrustN(flatMask)), ...
            VariableNames=["Source", "Flight", "Segment", "Samples", ...
            "HeightMeanM", "HeightDetrendStdM", ...
            "TASMeanMps", "TASDetrendStdMps", ...
            "PitchMeanDeg", "PitchDetrendStdDeg", ...
            "RollMeanDeg", "ElevatorMeanDeg", ...
            "ElevatorDetrendStdDeg", "CanardMeanDeg", ...
            "ThrottleMean", "ThrustMeanN"])]; %#ok<AGROW>
    end

    % 转弯指标使用共同任务折线的内部顶点。它描述闭环圆弧，不用于
    % 反推气动一致性；等效半径由协调转弯关系V^2/(g*tan|phi|)估计。
    for vertex = 2:size(routePoints, 1)-1
        vertexDistanceM = hypot(eastM - routePoints(vertex, 1), ...
            northM - routePoints(vertex, 2));
        turnMask = airborne & vertexDistanceM <= 750 & ...
            abs(one.RollDeg) >= 5;
        if nnz(turnMask) < 10
            continue
        end
        rollRadForRadius = deg2rad(abs(one.RollDeg(turnMask)));
        radiusSamplesM = one.TASMps(turnMask).^2 ./ ...
            (gravityMps2 * max(tan(rollRadForRadius), tan(deg2rad(5))));
        turnRows = find(turnMask);
        turnMetrics = [turnMetrics; table( ...
            one.Source, one.Name, vertex, nnz(turnMask), ...
            min(vertexDistanceM(turnMask)), ...
            vertexDistanceM(turnRows(1)), ...
            vertexDistanceM(turnRows(end)), ...
            median(radiusSamplesM), prctile(radiusSamplesM, 25), ...
            prctile(radiusSamplesM, 75), ...
            max(abs(one.RollDeg(turnMask))), ...
            mean(one.TASMps(turnMask)), ...
            one.TimeS(turnRows(end)) - one.TimeS(turnRows(1)), ...
            VariableNames=["Source", "Flight", "RouteVertex", "Samples", ...
            "MinimumVertexDistanceM", "TurnStartDistanceM", ...
            "TurnEndDistanceM", "EquivalentRadiusMedianM", ...
            "EquivalentRadiusP25M", "EquivalentRadiusP75M", ...
            "PeakRollDeg", "MeanTASMps", "TurnObservedDurationS"])]; %#ok<AGROW>
    end

    if one.Source == "px4"
        missionSequence = one.MissionSeq;
        switchRows = find(diff(missionSequence) ~= 0) + 1;
        for switchNumber = 1:numel(switchRows)
            switchRow = switchRows(switchNumber);
            if ~isfinite(missionSequence(switchRow-1)) || ...
                    ~isfinite(missionSequence(switchRow))
                continue
            end
            vertexDistanceM = hypot(routeEast - eastM(switchRow), ...
                routeNorth - northM(switchRow));
            missionSwitchMetrics = [missionSwitchMetrics; table( ...
                one.Name, one.TimeS(switchRow), ...
                missionSequence(switchRow-1), missionSequence(switchRow), ...
                min(vertexDistanceM), eastM(switchRow), northM(switchRow), ...
                one.HeightAGLM(switchRow), one.TASMps(switchRow), ...
                one.RollDeg(switchRow), ...
                VariableNames=["Flight", "TimeS", "PreviousMissionSeq", ...
                "NewMissionSeq", "NearestRouteVertexDistanceM", ...
                "EastM", "NorthM", "HeightAGLM", "TASMps", ...
                "RollDeg"])]; %#ok<AGROW>
        end
    end

    if one.Source == "px4"
        % 日志开始时飞机本来就在地面，不能把首个样本误判为接地。
        % 先确认至少经历过HeightAGL>=5 m的空中阶段，再找此后的首次
        % landed=true；这与动态验收脚本的真实接地定义保持一致。
        airborneStartIndex = find(~one.Landed & one.HeightAGLM >= 5, ...
            1, "first");
        touchdownIndex = [];
        if ~isempty(airborneStartIndex)
            % 高速接地后PX4 land detector可能仍因水平运动保持landed=false，
            % 而鸭翼状态机已经由接地过载进入着陆序列。因此接地判据取
            % land detector与Gazebo真值AGL<=5 cm的并集。
            contactAfterFlight = one.Landed | one.HeightAGLM <= 0.05;
            touchdownRelative = find( ...
                contactAfterFlight(airborneStartIndex+1:end), 1, "first");
            if ~isempty(touchdownRelative)
                touchdownIndex = airborneStartIndex + touchdownRelative;
            end
        end
        if ~isempty(touchdownIndex)
            brakeIndex = find((1:sampleCount)' >= touchdownIndex & ...
                one.DeltaDocDeg(:, 4) <= -40, 1, "first");
            if isempty(brakeIndex)
                brakeDelayS = NaN;
                brakeHoldS = 0;
            else
                brakeDelayS = one.TimeS(brakeIndex) - ...
                    one.TimeS(touchdownIndex);
                brakeHoldS = one.TimeS(end) - one.TimeS(brakeIndex);
            end
            touchdownMetrics = [touchdownMetrics; table( ...
                one.Name, one.TimeS(touchdownIndex), ...
                one.TASMps(touchdownIndex), ...
                one.HeightAGLM(touchdownIndex), ...
                one.RollDeg(touchdownIndex), ...
                one.PitchDeg(touchdownIndex), ...
                one.DeltaDocDeg(touchdownIndex, 2), ...
                one.DeltaDocDeg(touchdownIndex, 4), ...
                brakeDelayS, brakeHoldS, ...
                VariableNames=["Flight", "TouchdownTimeS", ...
                "TouchdownTASMps", "TouchdownHeightM", ...
                "TouchdownRollDeg", "TouchdownPitchDeg", ...
                "TouchdownElevatorDeg", "TouchdownCanardDeg", ...
                "CanardBrakeDelayS", "CanardBrakeHoldS"])]; %#ok<AGROW>
        end
    end

    trackResults(caseIndex).Source = one.Source;
    trackResults(caseIndex).Name = one.Name;
    trackResults(caseIndex).EastM = eastM;
    trackResults(caseIndex).NorthM = northM;
    trackResults(caseIndex).ProgressM = progressM;
    trackResults(caseIndex).CrossTrackM = crossTrackM;
    trackResults(caseIndex).SegmentIndex = segmentIndex;
    trackResults(caseIndex).AlongSegmentM = alongSegmentM;
    trackResults(caseIndex).Airborne = airborne;
end

%% 5.1 重复性及翔仪-PX4配对差异
pairMetrics = table;
pairList = nchoosek(1:numel(trackResults), 2);
for pairNumber = 1:size(pairList, 1)
    firstIndex = pairList(pairNumber, 1);
    secondIndex = pairList(pairNumber, 2);
    first = trackResults(firstIndex);
    second = trackResults(secondIndex);
    firstCase = flightCases(firstIndex);
    secondCase = flightCases(secondIndex);

    firstMask = first.Airborne;
    secondMask = second.Airborne;
    [firstProgress, firstOrder] = sort(first.ProgressM(firstMask));
    [firstProgress, uniqueFirst] = unique(firstProgress, "stable");
    firstRows = find(firstMask);
    firstRows = firstRows(firstOrder(uniqueFirst));
    [secondProgress, secondOrder] = sort(second.ProgressM(secondMask));
    [secondProgress, uniqueSecond] = unique(secondProgress, "stable");
    secondRows = find(secondMask);
    secondRows = secondRows(secondOrder(uniqueSecond));

    progressStart = max(firstProgress(1), secondProgress(1));
    progressEnd = min(firstProgress(end), secondProgress(end));
    progressGrid = (ceil(progressStart / 50) * 50:50: ...
        floor(progressEnd / 50) * 50)';
    if numel(progressGrid) < 10
        continue
    end

    firstEast = interp1(firstProgress, first.EastM(firstRows), ...
        progressGrid, "linear");
    firstNorth = interp1(firstProgress, first.NorthM(firstRows), ...
        progressGrid, "linear");
    secondEast = interp1(secondProgress, second.EastM(secondRows), ...
        progressGrid, "linear");
    secondNorth = interp1(secondProgress, second.NorthM(secondRows), ...
        progressGrid, "linear");
    horizontalDifference = hypot(firstEast - secondEast, ...
        firstNorth - secondNorth);

    stateNames = ["HeightAGLM", "TASMps", "RollDeg", "PitchDeg"];
    stateRMSE = zeros(1, 4);
    for stateNumber = 1:4
        firstValue = interp1(firstProgress, ...
            firstCase.(stateNames(stateNumber))(firstRows), ...
            progressGrid, "linear");
        secondValue = interp1(secondProgress, ...
            secondCase.(stateNames(stateNumber))(secondRows), ...
            progressGrid, "linear");
        stateRMSE(stateNumber) = sqrt(mean( ...
            (firstValue - secondValue).^2));
    end

    pairType = "cross_source";
    if first.Source == second.Source
        pairType = "repeatability";
    end
    pairMetrics = [pairMetrics; table( ...
        pairType, first.Name, second.Name, numel(progressGrid), ...
        sqrt(mean(horizontalDifference.^2)), ...
        prctile(horizontalDifference, 95), max(horizontalDifference), ...
        stateRMSE(1), stateRMSE(2), stateRMSE(3), stateRMSE(4), ...
        VariableNames=["PairType", "FirstFlight", "SecondFlight", ...
        "ProgressSamples", "HorizontalRMSM", "HorizontalP95M", ...
        "HorizontalMaxM", "HeightRMSEM", "TASRMSEMps", ...
        "RollRMSEDeg", "PitchRMSEDeg"])]; %#ok<AGROW>
end

%% 5.2 航迹和状态图片
trackColors = [ ...
    0.0000, 0.4470, 0.7410; ...
    0.0000, 0.6200, 0.4500; ...
    0.8500, 0.3250, 0.0980; ...
    0.6350, 0.0780, 0.1840];

figureHandle = figure("Visible", "off", ...
    "Position", [100, 100, 1300, 900]);
axisHandle = axes(figureHandle);
plot(axisHandle, routeEast, routeNorth, "k--", "LineWidth", 1.5, ...
    "DisplayName", "任务折线");
hold(axisHandle, "on");
for caseIndex = 1:numel(trackResults)
    airborne = trackResults(caseIndex).Airborne;
    plot(axisHandle, trackResults(caseIndex).EastM(airborne), ...
        trackResults(caseIndex).NorthM(airborne), ...
        "Color", trackColors(caseIndex, :), "LineWidth", 1.0, ...
        "DisplayName", trackResults(caseIndex).Name);
end
hold(axisHandle, "off");
axis(axisHandle, "equal");
grid(axisHandle, "on");
xlabel(axisHandle, "东向 / m");
ylabel(axisHandle, "北向 / m");
title(axisHandle, "翔仪与PX4 100 kg共同任务ENU轨迹");
legend(axisHandle, "Location", "best");
exportgraphics(figureHandle, fullfile(closedLoopOutputDir, ...
    "trajectory_enu_comparison.png"), "Resolution", 200);
close(figureHandle);

figureHandle = figure("Visible", "off", ...
    "Position", [100, 100, 1400, 900]);
axisHandle = axes(figureHandle);
plot3(axisHandle, routeEast, routeNorth, routeAltitude, ...
    "k--", "LineWidth", 1.5, "DisplayName", "任务点高度");
hold(axisHandle, "on");
for caseIndex = 1:numel(trackResults)
    airborne = trackResults(caseIndex).Airborne;
    plot3(axisHandle, trackResults(caseIndex).EastM(airborne), ...
        trackResults(caseIndex).NorthM(airborne), ...
        flightCases(caseIndex).HeightAGLM(airborne), ...
        "Color", trackColors(caseIndex, :), "LineWidth", 1.0, ...
        "DisplayName", trackResults(caseIndex).Name);
end
hold(axisHandle, "off");
grid(axisHandle, "on");
view(axisHandle, 42, 28);
xlabel(axisHandle, "东向 / m");
ylabel(axisHandle, "北向 / m");
zlabel(axisHandle, "相对地面高度 / m");
title(axisHandle, "翔仪与PX4 100 kg三维任务轨迹");
legend(axisHandle, "Location", "best");
exportgraphics(figureHandle, fullfile(closedLoopOutputDir, ...
    "trajectory_3d_comparison.png"), "Resolution", 200);
close(figureHandle);

figureHandle = figure("Visible", "off", ...
    "Position", [100, 100, 1500, 900]);
layout = tiledlayout(figureHandle, 2, 2, ...
    "TileSpacing", "compact", "Padding", "compact");
stateNames = ["HeightAGLM", "TASMps", "RollDeg", "PitchDeg"];
stateLabels = ["高度 / m", "TAS / (m/s)", "滚转角 / deg", "俯仰角 / deg"];
for stateNumber = 1:4
    axisHandle = nexttile(layout);
    hold(axisHandle, "on");
    for caseIndex = 1:numel(trackResults)
        airborne = trackResults(caseIndex).Airborne;
        plot(axisHandle, trackResults(caseIndex).ProgressM(airborne), ...
            flightCases(caseIndex).(stateNames(stateNumber))(airborne), ...
            "Color", trackColors(caseIndex, :), "LineWidth", 0.9, ...
            "DisplayName", trackResults(caseIndex).Name);
    end
    hold(axisHandle, "off");
    grid(axisHandle, "on");
    xlabel(axisHandle, "航线累计进度 / m");
    ylabel(axisHandle, stateLabels(stateNumber));
    title(axisHandle, stateLabels(stateNumber));
    if stateNumber == 1
        legend(axisHandle, "Location", "best");
    end
end
title(layout, "按共同航线进度对齐的飞行状态");
exportgraphics(figureHandle, fullfile(closedLoopOutputDir, ...
    "states_vs_route_progress.png"), "Resolution", 200);
close(figureHandle);

%% 5.3 保存闭环结果
writetable(trackMetrics, fullfile(closedLoopOutputDir, ...
    "track_metrics.csv"));
writetable(segmentMetrics, fullfile(closedLoopOutputDir, ...
    "segment_metrics.csv"));
writetable(turnMetrics, fullfile(closedLoopOutputDir, ...
    "turn_metrics.csv"));
writetable(missionSwitchMetrics, fullfile(closedLoopOutputDir, ...
    "mission_switch_metrics.csv"));
writetable(pairMetrics, fullfile(closedLoopOutputDir, ...
    "progress_aligned_pair_metrics.csv"));
writetable(flatSegmentMetrics, fullfile(closedLoopOutputDir, ...
    "flat_segment_metrics.csv"));
writetable(touchdownMetrics, fullfile(closedLoopOutputDir, ...
    "touchdown_canard_metrics.csv"));

% 航迹逐样本结果已经由图片及CSV表达；MAT仅保存轻量制表结果，
% 避免Windows MATLAB经WSL UNC路径写大型-v7.3文件的兼容性问题。
save(fullfile(closedLoopOutputDir, "closed_loop_results.mat"), ...
    "trackMetrics", "segmentMetrics", "turnMetrics", ...
    "missionSwitchMetrics", "pairMetrics", "flatSegmentMetrics", ...
    "touchdownMetrics", "routeLatitude", "routeLongitude", ...
    "routeAltitude", "-v7");

closedLoopSummary = struct;
closedLoopSummary.GeneratedBy = "MATLAB R2025a sequential scripts";
closedLoopSummary.PlanFile = planFile;
closedLoopSummary.RoutePointCount = numel(routeLatitude);
closedLoopSummary.RouteLengthM = routeCumulative(end);
closedLoopSummary.TrackMetrics = table2struct(trackMetrics);
closedLoopSummary.SegmentMetrics = table2struct(segmentMetrics);
closedLoopSummary.TurnMetrics = table2struct(turnMetrics);
closedLoopSummary.MissionSwitchMetrics = ...
    table2struct(missionSwitchMetrics);
closedLoopSummary.PairMetrics = table2struct(pairMetrics);
closedLoopSummary.FlatSegmentMetrics = table2struct(flatSegmentMetrics);
closedLoopSummary.TouchdownMetrics = table2struct(touchdownMetrics);
closedLoopSummary.Interpretation = ...
    "Closed-loop differences include controller, guidance and mission-state logic; they are not an aerodynamic-model pass/fail test.";

jsonText = jsonencode(closedLoopSummary, "PrettyPrint", true);
fileID = fopen(fullfile(closedLoopOutputDir, ...
    "closed_loop_summary.json"), "w", "n", "UTF-8");
assert(fileID >= 0, "无法创建闭环对比JSON摘要。");
fprintf(fileID, "%s\n", jsonText);
fclose(fileID);

disp("闭环对比输出完成：")
disp(closedLoopOutputDir)
disp(trackMetrics)
disp(pairMetrics)
